messages:
  # Если игрок попытается создать маркер города не в верхнем мире
  markerWorldName: "Маркер может быть создан только в верхнем мире"

  # Если игрок попытается создать ветку не в аду
  linesWorldName: "Ветка может быть создана только в нижнем мире"

  # При создании ветки строка с назанием пустая
  creatingLine-emptyLines: "Строка названия не может быть пустой!"

  # При создании маркера
  createdMarker: "Создан новый маркер <id> на карте."

  # Поставлено меньше двух маркеров ветки (corners) для создания ветки
  atLeast-two-corners: "Добавьте не меньше двух маркеров через <createcorner> тег на табличке для создания линии"

  # Если табличку маркера/ветки попытается сломать не ее владелец
  onlyOwner-canBreak: "Только владелец может убрать данную табличку!"

utils:
  # Название мира для маркеров
  worldName-markers: "world"

  # Название мира для создания веток
  worldName-lines: "world_nether"

tags:
  create-marker: "<marker>"
  create-line: "<loop>"
  create-corner: "<point>"

#ДОДЕЛАТЬ БД
#ДОДЕЛАТЬ ИВЕНТЫ ЛОМАНИЯ ЗАЩИЩЁННЫХ ТАБЛИЧЕК (ТОЛЬКО ГЛАВНАЯ)
#СДЕЛАТЬ ТАБЛИЧКИ НЕРЕДАКТИРУЕМЫМИ
#АДМИНЫ МОГУТ ЛОМАТЬ ТАБЛИЧКИ ДРУГИХ ИГРОКОВ
#
